android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/applicaster/xray/example/App.kt
android/app/src/main/java/com/applicaster/xray/example/ui/EventLogFragment.kt
android/app/src/main/java/com/applicaster/xray/example/ui/MainActivity.kt
android/notification/src/main/java/com/applicaster/xray/ui/notification/XRayNotification.kt

Initialize XRay in base application class, and make Show notification action button configurable by user.

* initialize XRay in base application class

---

android/app/build.gradle
android/app/src/main/java/com/applicaster/xray/example/ui/EventRecyclerViewAdapter.kt
android/app/src/main/java/com/applicaster/xray/example/ui/MainActivity.kt
android/app/src/main/java/com/applicaster/xray/example/utility/Format.kt
android/app/src/main/res/layout/fragment_event_log.xml
android/app/src/main/res/values/arrays.xml
android/app/src/main/res/values/colors.xml

Better demo log UI: colored list view entries, copy on touch

Feat:better demo UI

---

apple/Extensions/LoggerNavigationController/Cells/LoggerCell/LoggerCell.swift
apple/Extensions/LoggerNavigationController/Cells/LoggerCell/LoggerCell.xib
apple/Extensions/LoggerNavigationController/ViewControllers/LoggerViewController/LoggerViewController.swift
apple/Extensions/LoggerNavigationController/ViewControllers/LoggerViewController/LoggerViewController.xib

fixes for cells presentation

---

apple/Extensions/LoggerNavigationController/Cells/LoggerCell/LoggerCell.swift
apple/Extensions/LoggerNavigationController/Cells/LoggerCell/LoggerCell.xib
apple/Extensions/LoggerNavigationController/LoggerNavigationController.swift
apple/Extensions/LoggerNavigationController/ViewControllers/LoggerViewController/LoggerViewCollectionFlowLayout.swift
apple/Extensions/LoggerNavigationController/ViewControllers/LoggerViewController/LoggerViewController.swift
apple/Extensions/LoggerNavigationController/ViewControllers/LoggerViewController/LoggerViewController.xib
apple/LoggerInfo.podspec
apple/Podfile
apple/Reporter.podspec
apple/XrayLogger.podspec

fixes
source https://stackoverflow.com/questions/44187881/uicollectionview-full-width-cells-allow-autolayout-dynamic-height/44352072

Fix collection presentation

---

.circleci/config.yml
android/build.gradle
android/gradle/constants.gradle
android/gradle/publish.gradle
android/reflectionformatter/build.gradle
android/xray-core/build.gradle
android/xray-core/gradle.properties
android/xray-crashreporter/build.gradle
android/xray-notification/build.gradle
android/xray-notification/gradle.properties
android/xray-react-native/build.gradle

Publish some of the modules artifacts to bintray using CircleCI

Feat: maven publishing

---

.circleci/config.yml
android/build.gradle
android/gradle/constants.gradle
android/gradle/publish.gradle
android/reflectionformatter/src/main/java/com/applicaster/xray/formatters/message/reflactionformatter/NamedReflectionMessageFormatter.kt

Fix a number of path issues, pom dependency generation, and lint errors for CI

Fix: CI publishing

---

android/xray-react-native/src/main/java/com/applicaster/xray/reactnative/XRayLoggerBridge.kt

RN can try to pass arbitrary data types as data or context, but we only expect maps. Now we validate it and complain.

Fix: check optional argument types when passing from RN

---

android/build.gradle
android/gradle.properties
android/xray-notification/build.gradle

move xRayPublishing flag to gradle.properties and access it from the root project

Fix: move xRayPublishing flag to gradle.properties

---

android/build.gradle
android/gradle.properties
android/xray-core/build.gradle
android/xray-crashreporter/build.gradle
android/xray-notification/build.gradle
android/xray-react-native/build.gradle

Fix maven publishing setup

---

apple/XrayLogger/Sinks/FileJSON.swift

Add clean json file event in order to see that clean operation completed (also for qa to verify the clean of json file)

Add clean json file event

---

android/xray-ui/build.gradle
android/xray-ui/src/androidTest/java/com/applicaster/xray/ui/ExampleInstrumentedTest.kt
android/xray-ui/src/main/AndroidManifest.xml
android/xray-ui/src/main/java/com/applicaster/xray/ui/adapters/EventRecyclerViewAdapter.kt
android/xray-ui/src/main/java/com/applicaster/xray/ui/adapters/ViewsPagerAdapter.java
android/xray-ui/src/main/java/com/applicaster/xray/ui/fragments/EventLogFragment.kt
android/xray-ui/src/main/java/com/applicaster/xray/ui/fragments/FileLogFragment.kt
android/xray-ui/src/main/java/com/applicaster/xray/ui/utility/FilteredEventList.kt
android/xray-ui/src/main/res/drawable/ic_baseline_filter_list_24.xml
android/xray-ui/src/main/res/layout/xray_fragment_event_log_entry.xml
android/xray-ui/src/main/res/layout/xray_fragment_event_log_list.xml
android/xray-ui/src/test/java/com/applicaster/xray/ui/ExampleUnitTest.kt

Filters and details are added to current session event log fragment

feat: add filters and details in Events Fragment

---

apple/Extensions/LoggerNavigationController/ViewControllers/LoggerViewController/LoggerViewController.swift

fix for subsystem search - lowercasing the subsystem to check if contains test that was already lowercased

fix for subsystem search

---

apple/Extensions/LoggerNavigationController/ViewControllers/DetailedLoggerViewController/DetailedLoggerViewController.swift
apple/Extensions/LoggerNavigationController/ViewControllers/DetailedObjectLoggerViewController/DetailedObjectLoggerViewController.swift

set background color for cell to transparent as it shows gray on testflight builds

fix: set background color for cell to transparent as it shows gray on testflight builds

---

apple/Extensions/LoggerNavigationController/ViewControllers/DetailedLoggerViewController/DetailedLoggerViewController.swift
apple/Extensions/LoggerNavigationController/ViewControllers/DetailedObjectLoggerViewController/DetailedObjectLoggerViewController.swift

add more bg fixes

---

android/xray-ui/src/main/java/com/applicaster/xray/ui/fragments/FileLogFragment.kt
android/xray-ui/src/main/res/layout/xray_fragment_log.xml

Limit size of the log we attempt to load automatically to 100kb. Otherwise it freezes the UI for a significant amount of time.

feat: prevent big logs from auto load in log file fragment

---

android/app/src/main/java/com/applicaster/xray/example/App.kt
android/xray-core/src/main/java/com/applicaster/xray/android/sinks/PackageFileLogSink.java

Add optional log file limit that will trigger basic truncate.

feat: file log truncate log limit

---

android/app/src/main/java/com/applicaster/xray/example/App.kt
android/xray-notification/src/main/java/com/applicaster/xray/ui/notification/NotificationReceiver.java
android/xray-notification/src/main/java/com/applicaster/xray/ui/notification/XRayNotification.kt

Provide an easy way to override notification click event

feat: add default intent option to Notification extension

---

android/xray-ui/src/main/java/com/applicaster/xray/ui/adapters/EventRecyclerViewAdapter.kt

feat: display exception details in the UI

---

android/app/src/main/java/com/applicaster/xray/example/ui/MainActivity.kt
android/app/src/main/res/layout/activity_main.xml
android/xray-ui/src/main/java/com/applicaster/xray/ui/views/DefaultViewPager.java

feat: add DefaultViewPager to automate UI setup

---

apple/ExampleProject/Podfile
apple/Extensions/LoggerNavigationController/ViewControllers/DetailedLoggerViewController/DetailedLoggerViewController.swift
apple/Extensions/LoggerNavigationController/Views/SortLogsView/SortLogsHelper.swift
apple/LoggerInfo.podspec
apple/Reporter.podspec
apple/XrayLogger.podspec

feat: Prepare to iOS 12

---

apple/Extensions/LoggerNavigationController/ViewControllers/LoggerViewController/LoggerViewController.swift

feat: add close button action

---

android/xray-ui/src/main/java/com/applicaster/xray/ui/adapters/EventRecyclerViewAdapter.kt
android/xray-ui/src/main/java/com/applicaster/xray/ui/fragments/EventLogFragment.kt
android/xray-ui/src/main/java/com/applicaster/xray/ui/fragments/model/FilteredEventList.kt
android/xray-ui/src/main/java/com/applicaster/xray/ui/fragments/model/SearchState.kt
android/xray-ui/src/main/res/drawable/ic_baseline_search_24.xml
android/xray-ui/src/main/res/drawable/ic_baseline_search_filter_24.xml
android/xray-ui/src/main/res/drawable/ic_baseline_skip_next_24.xml
android/xray-ui/src/main/res/drawable/ic_baseline_skip_previous_24.xml
android/xray-ui/src/main/res/layout/xray_fragment_event_log_list.xml
android/xray-ui/src/main/res/values/arrays.xml

Now user can search for text in filtered list in selected fields and navigate between found entries.

feat: powerfull search

---

android/xray-ui/src/main/java/com/applicaster/xray/ui/fragments/EventLogFragment.kt
android/xray-ui/src/main/java/com/applicaster/xray/ui/utility/Format.kt
android/xray-ui/src/main/java/com/applicaster/xray/ui/utility/SharedFileHelper.kt
android/xray-ui/src/main/res/drawable/ic_baseline_share_24.xml
android/xray-ui/src/main/res/layout/xray_fragment_event_log_list.xml
android/xray-ui/src/main/res/values/arrays.xml
android/xray-ui/src/main/res/values/strings.xml

Now its possible to export in-memory log as a json with different options and targets.

feat: export memory log

---

android/xray-ui/src/main/java/com/applicaster/xray/ui/fragments/FileLogFragment.kt
android/xray-ui/src/main/java/com/applicaster/xray/ui/utility/SharedFileHelper.kt
android/xray-ui/src/main/res/drawable/ic_baseline_delete_24.xml
android/xray-ui/src/main/res/layout/xray_fragment_log.xml

feat: export file log

---

apple/Extensions/Reporter/Email.swift
apple/Extensions/Reporter/Reporter.swift

Move email check before creating unified log file

chore: Move email check before creating unified log file

---

apple/Extensions/Reporter/Reporter.swift

fix for email sending on simulator

fix for email sending on simulator

---

android/xray-react-native/src/main/java/com/applicaster/xray/reactnative/XRayLoggerBridge.kt

Incoming RN data validation improved

Fix check rn

---

apple/Extensions/LoggerNavigationController/Cells/FilterDataCell/FilterDataCell.swift
apple/Extensions/LoggerNavigationController/ViewControllers/FilterViewController/FilterViewController.swift
apple/Extensions/LoggerNavigationController/Views/SortLogsView/SortLogsHelper.swift
apple/Extensions/LoggerNavigationController/Views/SortNetworkRequestsView/SortNetworkRequestsHelper.swift

Updates for deprecations in Xcode 13

chore: Updates for deprecations in Xcode 13
